### ISSUE TITLE
Seem to be stuck in an infinite loop after login

### ISSUE THREAD

**Issue by frankcaron** [salesforceidentity/embedded-login-example#2]
After implementing the embeddable login JS, I'm stuck in something of an infinite loop. Logging in results in the following console logs endlessly writing:

"entering xauth retrieve function"
"you got logged in"

It seems that the xauth server code doesn't work the same way anymore on recent versions of Chrome or Safari? I've tried in every permutation of normal and incognito tab as well as tried clearing my cache. 

I just did a fresh deploy after 4 hours of attempting to implement myself in Node from scratch using the docs on developer.salesforce.com, and I've gotten stuck at the same impasse on both fronts.

**Comment by cmortimore** [comment]
This should be fixed tomorrow.

**Comment by cmortimore** [comment]
Sorry about the loop. Issue with the release which we have corrected and is working it’s way out.

**Comment by frankcaron** [comment]
Thanks @cmortimore! Out of curiosity, are there any known issues with the callback handling with specific app stacks? It seems like I'm actually getting a payload back when the callback of my Node JS app is hit, but that payload is lost in the redirect to the main index page and it sits idly waiting for me to log in again.

Reference is here: https://github.com/frankcaron/salesforce-embedded-login-example

**Comment by cmortimore** [comment]
Yeah, it’s a known in that part of the code.  There’s an issue iterating over the token handling once you are logged in.   My advice is to sit tight and it will fix itself tomorrow if your at in dev/testing.   If you are suffering a production outage write me back and let me know and we can get that unstuck.

**Comment by frankcaron** [comment]
Not a production issue but a big customer end-to-end demo for Monday. I'll check back in tomorrow. :)

**Comment by cmortimore** [comment]
As soon as it’s on Winter20 it should be fixed.  Summer19 is briefly broken.

**Comment by frankcaron** [comment]
Hrm. I’m on Winter 20 and it’s still not working for me. I’m not seeing that infinite loop of the logs anymore, but the payload is still lost upon direct from the callback page.

**Comment by frankcaron** [comment]
User error. I had the URL for allowed-domains configured in my environment variables to include the "https".
